### PR TITLE
forward remaining_args to cucumber

### PR DESCRIPTION
**Pull request by git2samus**
this is necessary in order to tell cucumber to run a subset of the features instead of the whole suite.

### CODE REVIEW

**Comment by imkira** [comment]
Hello git2samus, and thank you very much for your pull request.

Regarding the "run a subset of the features instead of the whole suite", I suppose you know about the existence of cucumber @tags for helping specify which features/scenarios you want to include or filter out (specifying the -t parameter to cucumber).
Also, if you are a rake user you can also use the rake tasks provided with cukunity (by requiring cukunity/tasks/cucumber.rake), but that is useless since it is not used by cukunity binary.

Anyway, your commit makes perfect sense from the point of view of someone using just the cukunity binary, so I wish to merge in your pull request but before I would like to discuss with you about the help screen regarding the features command.

You wrote like:

```
features [--path=< path >] [<cucumber-opts> ...]
```

And if I call it like:

```
features --path=whatever/features whatever/specific.feature
```

I think it may lead to some doubt: does "--path=" mean the whole directory will it executed?

And what I think about it is that since we pass it as the "--require" argument to cucumber, probably we should rename it to something like "--base" (the base directory for the features) or something else more appropriate.

Also, regarding the use of "<cucumber-opts>", since "--parameter" style usage is not possible because it is picked by cukunity's optparse, we can only pass "raw" arguments (the parameter-less arguments in remaining_args), so maybe I would just use what cucumber uses [ [FILE|DIR|URL][:LINE[:LINE]*] ]+ but make it more "human readable".

In sum, what do you think about this:

```
features [--base=<path>] [<dir/containing/features | path/to/specific.feature> ...]
```

**Comment by git2samus** [comment]
what is the purpose of that path? I thought it was used to place the features somewhere else but, even on the current (unpatched) version you **can't** run cukunity if you don't have a "features" directory at the root of the project, no matter what you give as <path>

regarding the raw arguments, that's exactly what I'm looking for; cukunity is a wrapper over cucumber so I expect it to work exactly like it, that's why I was surprised when cukunity didn't allowed the `[ [FILE|DIR|URL][:LINE[:LINE]*] ]+` syntax.

the point is: people familiar with cucumber should be able to use cukunity without learning anything new, I think it's not a good idea to have a new "human readable" syntax here instead of the original everyone will expect to be available.

**Comment by git2samus** [comment]
here's some ideas about dealing with extra arguments with OptionParser: http://stackoverflow.com/questions/3642331/can-optparse-skip-unknown-options-to-be-processed-later-in-a-ruby-program

to separate cukunity and cucumber args with `--` seems a good idea, what do you think?

**Comment by imkira** [comment]
The purpose of path is to load all the required files for running some/all of your features.
[ [FILE|DIR|URL][:LINE[:LINE]*] ]+ would be for selecting which features you want to test (all if none specified).

I think using "--" is a good idea, as it is also used in many other command line tools for separating arguments otherwise recognized as options from other special purpose arguments.

Could you try implementing it in your repo and send me a pull request?

Thanks

**Comment by git2samus** [comment]
sure, I'll open a different pull since this no longer conflicts with the original <path> we had before.

**Pull request closed without merging**
